ISCAE.Web/Controllers/AdministrateurController.cs
using ISCAE.Web.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ISCAE.Web.Controllers
{
    [SessionFilter()]
    [AdministrateurFilter()]
    public class AdministrateurController : Controller
    {
        
        // GET: Administrateur
        public ActionResult Index()
        {
            return View();
        }
    }
}

ISCAE.Web/Controllers/AnnonceController.cs
using ISCAE.Business.Services;
using ISCAE.Web.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ISCAE.Web.Controllers
{
    [SessionFilter()]
    public class AnnonceController : Controller
    {
        private IAnnonceService _annonceService;
        private IResultatService _resultatService;
        private ISpecialiteService _specialiteService;
        public AnnonceController(IAnnonceService annonceService, IResultatService resultatService, ISpecialiteService specialiteService)
        {
            _annonceService = annonceService;
            _resultatService = resultatService;
            _specialiteService = specialiteService;
        }
        // GET: Annonce
        public ActionResult Index()
        {
            ViewBag.Avis = _annonceService.GetAll().OrderByDescending(o=>o.AnnonceId).Take(10).ToList();
            ViewBag.Resultats = _resultatService.GetAll().OrderByDescending(o => o.ResultatId).Take(10).ToList();
            ViewBag.Specialites = _specialiteService.GetAll().ToList();
            return View();
        }
        public ActionResult Avis()
        {
            return View();
        }
    }
}

ISCAE.Web/Controllers/EtudiantController.cs
using ISCAE.Business.Services;
using ISCAE.Data;
using ISCAE.Web.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ISCAE.Web.Controllers
{
    [SessionFilter()]
    [EtudiantFilter()]
    public class EtudiantController : Controller
    {
        private IEtudiantService _etudiantService;
        private IDocumentNonOfficielService _documentNonOfficielService;
        private IDocumentOfficielService _documentOfficielService;
        private IMessageService _messageService;
        private IAnnonceService _annonceService;
        private IProfesseurService _professeurService;
        private INotificationService _notificationService;
        private IQuestionService _questionService;
        private IModuleService _moduleService;
        private ISpecialiteModuleService _specialiteModuleService;

        public EtudiantController(IEtudiantService etudiantService, IDocumentNonOfficielService documentNonOfficielService,
               IDocumentOfficielService documentOfficielService, IMessageService messageService, IModuleService moduleService,
               IAnnonceService annonceService, INotificationService notificationService, IQuestionService questionService,
               IProfesseurService professeurService, ISpecialiteModuleService specialiteModuleService)
        {
            _etudiantService = etudiantService;
            _documentNonOfficielService = documentNonOfficielService;
            _documentOfficielService = documentOfficielService;
            _messageService = messageService;
            _annonceService = annonceService;
            _notificationService = notificationService;
            _questionService = questionService;
            _moduleService = moduleService;
            _professeurService = professeurService;
            _specialiteModuleService = specialiteModuleService;
        }
        // GET: Etudiant

        public ActionResult Index()
        {
            
            Etudiant user = (Etudiant)Session["user"];
            // Notifications
            List<Notification> notifications = _notificationService.GetUnreadNotifications(user.EtudiantId).ToList();
            int notificationCount = notifications.Count();

            // Documents
            List<DocumentNonOfficiel> documents = _documentNonOfficielService.GetNonValidDocument(1, 10).ToList();

            // Messages
            List<Message> messages = _messageService.GetMessagesBySpecialiteAndNiveau(user.SpecialiteId, user.Niveau,1,5).ToList();
            int messageCount = messages.Count();

            // Annonces
            List<Annonce> annonces = _annonceService.GetAll().OrderByDescending(o => o.AnnonceId).Take(5).ToList();

            // Discussions
            List<Question> questions = _questionService.GetAll().OrderByDescending(o => o.QuestionId).Take(10).ToList();

            // Modules
            List<SpecialiteModule> data = _specialiteModuleService.GetSpecialiteModulesByNiveau(user.SpecialiteId, user.Niveau).ToList();
            List<Module> modules = new List<Module>();
            foreach (SpecialiteModule sm in data)
            {
                modules.Add(_moduleService.Get(sm.ModuleId));
            }
            // Model
            Session["notifications"] = notifications;
            Session["notificationCount"] = notificationCount;
            Session["messageCount"] = messageCount;
            ViewBag.documents = documents;
            ViewBag.messages = messages;
            ViewBag.messageCount = messageCount;
            ViewBag.annonces = annonces;
            ViewBag.questions = questions;
            ViewBag.modules = modules;
            ViewBag.professeurs = _professeurService.GetProfesseursBySpecialiteAndNiveau(user.SpecialiteId,user.Niveau);
            ViewBag.etudiants = _etudiantService.Find(o=>o.SpecialiteId==user.SpecialiteId && o.Niveau == user.Niveau).ToList();
            return View(user);
        }
        public ActionResult UserProfile()
        {
            
            return View((Etudiant)Session["user"]);
        }
        [HttpPost]
        public ActionResult UserProfile(string email, string telephone)
        {
            Etudiant user = (Etudiant)Session["user"];
            if (email == null || email.Equals(""))
            {
                return View(user);
            }
            
            user.Email = email;
            user.Telephone = telephone;
            user = _etudiantService.Edit(user);
            if(user == null)
            {
                user = (Etudiant)Session["user"];
                return View(user);
            }
            Session["user"] = user;
            return View(user);
        }
        [HttpPost]
        public ActionResult Avatar(HttpPostedFileBase image)
        {
            Etudiant user = (Etudiant)Session["user"];
            
            return View(user);
        }
    }
}

ISCAE.Web/Controllers/ProfesseurController.cs
using ISCAE.Web.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ISCAE.Web.Controllers
{
    [SessionFilter()]
    public class ProfesseurController : Controller
    {
        // GET: Professeur
        public ActionResult Index()
        {
            return View();
        }
    }
}

ISCAE.Web/Views/Shared/_AdministrateurLayout.cshtml
@using ISCAE.Data;
@{
    Administrateur user = ((Administrateur)Session["user"]);
    List<Notification> notifications = (List<Notification>)Session["notifications"];
    int notificationCount = (int)Session["notificationCount"];
    
 }
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>@user.Login | @Html.ViewBag.Title</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  @Styles.Render("~/Content/user")

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition skin-green-light sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href='@Url.Action("Index","Administrateur")' class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini">ISCAE</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg">ISCAE</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
    <!-- Notifications: style can be found in dropdown.less -->
           @{
               if (notificationCount > 0)
               {
                <li class="dropdown notifications-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        <span class="label label-warning">@notificationCount</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">Vous avez @notificationCount notifications</li>
                        <li>
                            <!-- inner menu: contains the actual data -->
                            <ul class="menu">
                                @{
                                    foreach (Notification n in notifications)
                                    {
                                        <li>
                                            <a href="@Url.Action("Notifications", "Notification", new { id = n.NotificationId})">
                                                <i class="fa fa-star text-aqua"></i> @n.Message
                                            </a>
                                        </li>
                                    }
                                }
                               
                            </ul>
                        </li>
                        <li class="footer"><a href="#">Afficher Tous</a></li>
                    </ul>
                </li>

               }
               else
               {
                <li class="dropdown notifications-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>

                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">Pas de notifications</li>
                        <li>
                            <!-- inner menu: contains the actual data -->
                            <ul class="menu">
                                <li>

                                </li>
                            </ul>
                        </li>
                        <li class="footer"><a href="#">View all</a></li>
                    </ul>
                </li>
               }
        }

                    <!-- User Account: style can be found in dropdown.less -->
            <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <img src="" class="user-image" alt="User Image">
                    <span class="hidden-xs">@user.Nom</span>
                </a>
                <ul class="dropdown-menu">
                    <!-- User image -->
                    <li class="user-header">
                        <img src="" class="img-circle" alt="User Image">
                        <p>
                            @user.Nom 
                        </p>
                    </li>

                    <!-- Menu Footer-->
                    <li class="user-footer">
                        <div class="pull-left">
                            <a href="#" class="btn btn-default btn-flat">Profile</a>
                        </div>
                        <div class="pull-right">
                            <a href="@Url.Action("Logout","Home")" class="btn btn-default btn-flat">Logout</a>
                        </div>
                    </li>
                </ul>
            </li>
        </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p>@user.Nom</p>
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <!-- search form -->
                <form action="#" method="get" class="sidebar-form">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </form>
                <!-- /.search form -->
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li class="header">MAIN NAVIGATION</li>
                    <li class="active">
                        <a href='@Url.Action("Index","Administrateur")'>
                            <i class="fa fa-home"></i> <span>Accueil</span>
                        </a>
                    </li>
                    <li class="treeview">
                        <a href='@Url.Action("Index","Document")'>
                            <i class="fa fa-book"></i>
                            <span>Documents</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href='@Url.Action("Officiel","Document")'><i class="fa fa-circle-o"></i>Ajouter par profs</a></li>
                            <li><a href='@Url.Action("NonOfficiel","Document")'>
                                <i class="fa fa-circle-o"></i> Ajouter par etudiant
                                    <span class="pull-right-container">
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </span>
                                </a>
                                <ul class="treeview-menu">
                                    <li><a href="@Url.Action("","")"><i class="fa fa-circle-o"></i> Documents Valide</a></li>
                                    <li><a href="@Url.Action("","")"><i class="fa fa-circle-o"></i> Documents Invalide</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href='@Url.Action("Index","Discussion")'>
                            <i class="fa fa-comments-o"></i>
                            <span>Discussions</span>
                        </a>

                    </li>
                    <li>
                        <a href='@Url.Action("Index","Annonce")'>
                            <i class="fa fa-flash"></i> <span>Annonces</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("","")"><i class="fa fa-circle-o"></i> Afficher tous</a></li>
                            <li><a href="@Url.Action("","")"><i class="fa fa-circle-o"></i> Ajouter un avis</a></li>
                            <li><a href="@Url.Action("","")"><i class="fa fa-circle-o"></i> Ajouter un resultat</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href='@Url.Action("Index","Message")'>
                            <i class="fa fa-envelope"></i> <span>Messages</span>
                            <span class="pull-right-container">
                                
                            </span>
                        </a>
                    </li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    @ViewBag.Title
                </h1>
            </section>
            <!-- Main content -->
            <section class="content">


                @RenderBody()
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>Copyright &copy; @DateTime.Now.Year ISCAE </strong>
        </footer>
        <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
        <!-- ./wrapper -->
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/user")
        @RenderSection("scripts", required: false)
</body>
</html>

ISCAE.Web/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ISCAE</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    @Styles.Render("~/Content/home")
    @Scripts.Render("~/bundles/modernizr")
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body class="hold-transition skin-green layout-top-nav">
    <div class="wrapper">
        @Html.Partial("_Navbar")
        <div class="content-wrapper">
            <div class="container">
                <!-- Main content -->
                <section class="content">
                    @RenderBody()
                </section>
                <!-- /.content -->
            </div>
            <!-- /.container -->
        </div>
        
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="container">
                <strong>Copyright &copy; @DateTime.Now.Year ISCAE.</strong> All rights
                reserved.
            </div>
            <!-- /.container -->
        </footer>
    </div>
    <!-- ./wrapper -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @*<script type="text/javascript">
        $(function () {
            $("#login_form").on("submit", function (e) {
                e.preventDefault();
                $("#loading").addClass("fa fa-refresh fa-spin");
                $("#connecter-btn").addClass("disabled");
                $.ajax({
                    url: this.action,
                    type: this.method,
                    data: { 'login' : $("#username").val(), 'password' : $("#password").val() },
                    success: function (data) {
                        $("#loading").removeClass("fa fa-refresh fa-spin");
                        $("#loading").text = "Success";
                        $("#connecter-btn").removeClass("disabled");
                    },
                    error: function () {
                        $("#loading").removeClass("fa fa-refresh fa-spin");
                        $("#loading").text = "Error";
                        $("#connecter-btn").removeClass("disabled");
                    }
                    
                });
            });
        });

    </script>*@
    
</body>
</html>

ISCAE.Web/Views/Shared/_ProfesseurLayout.cshtml
@using ISCAE.Data;
@{
    Professeur user = ((Professeur)Session["user"]);
    List<Notification> notifications = (List<Notification>)Session["notifications"];
    int notificationCount = (int)Session["notificationCount"];
  
 }
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>@user.Login | @Html.ViewBag.Title</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  @Styles.Render("~/Content/user")

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition skin-green sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href='@Url.Action("Index","Professeur")' class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini">ISCAE</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg">ISCAE</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
    <!-- Notifications: style can be found in dropdown.less -->
    @{
        if (notificationCount > 0)
        {
            <li class="dropdown notifications-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-bell-o"></i>
                    <span class="label label-warning">@notificationCount</span>
                </a>
                <ul class="dropdown-menu">
                    <li class="header">Vous avez @notificationCount notifications</li>
                    <li>
                        <!-- inner menu: contains the actual data -->
                        <ul class="menu">
                            @{
                                foreach (Notification n in notifications)
                                {
                                    <li>
                                        <a href="@Url.Action("Notifications", "Notification", new { id = n.NotificationId})">
                                            <i class="fa fa-star text-aqua"></i> @n.Message
                                        </a>
                                    </li>
                                }
                            }

                        </ul>
                    </li>
                    <li class="footer"><a href="#">Afficher Tous</a></li>
                </ul>
            </li>

        }
        else
        {
            <li class="dropdown notifications-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-bell-o"></i>
                    
                </a>
                <ul class="dropdown-menu">
                    <li class="header">Pas de notifications</li>
                    <li>
                        <!-- inner menu: contains the actual data -->
                        <ul class="menu">
                            <li>
                                
                            </li>
                        </ul>
                    </li>
                    <li class="footer"><a href="#">View all</a></li>
                </ul>
            </li>
        }
    }


                    <!-- User Account: style can be found in dropdown.less -->
            <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <img src="@Url.Content(user.ProfilePath)" class="user-image" alt="User Image">
                    <span class="hidden-xs">@user.Nom</span>
                </a>
                <ul class="dropdown-menu">
                    <!-- User image -->
                    <li class="user-header">
                        <img src="@Url.Content(user.ProfilePath)" class="img-circle" alt="User Image">
                        <p>
                           Professeur @user.Nom 
                        </p>
                    </li>

                    <!-- Menu Footer-->
                    <li class="user-footer">
                        <div class="pull-left">
                            <a href="#" class="btn btn-default btn-flat">Profile</a>
                        </div>
                        <div class="pull-right">
                            <a href="@Url.Action("Logout","Home")" class="btn btn-default btn-flat">Logout</a>
                        </div>
                    </li>
                </ul>
            </li>
        </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="@Url.Content(user.ProfilePath)" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p>@user.Nom</p>
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <!-- search form -->
                <form action="#" method="get" class="sidebar-form">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </form>
                <!-- /.search form -->
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li class="header">MAIN NAVIGATION</li>
                    <li class="active">
                        <a href='@Url.Action("Index","Etudiant")'>
                            <i class="fa fa-home"></i> <span>Accueil</span>
                        </a>
                    </li>
                    <li class="treeview">
                        <a href='@Url.Action("Index","Document")'>
                            <i class="fa fa-book"></i>
                            <span>Documents</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href='@Url.Action("Officiel","Document")'><i class="fa fa-circle-o"></i>Ajouter par profs</a></li>
                            <li><a href='@Url.Action("NonOfficiel","Document")'><i class="fa fa-circle-o"></i> Ajouter par etudiant</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-comments-o"></i>
                            <span>Discussions</span>
                        </a>

                    </li>
                    <li>
                        <a href='@Url.Action("Index","Annonce")'>
                            <i class="fa fa-flash"></i> <span>Annonces</span>
                        </a>
                    </li>
                    <li>
                        <a href='@Url.Action("Index","Message")'>
                            <i class="fa fa-envelope"></i> <span>Messages</span>
                        </a>
                    </li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    @ViewBag.Title
                </h1>
            </section>
            <!-- Main content -->
            <section class="content">


                @RenderBody()
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>Copyright &copy; @DateTime.Now.Year ISCAE </strong>
        </footer>
        <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
        <!-- ./wrapper -->
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/user")
        @RenderSection("scripts", required: false)
    
</body>
</html>